apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: webapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels: 
        app: webapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 3
