apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: webapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels: 
        app: webapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  replicas: 3
  selector:
    matchLabels:
      type: front-end
