apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
    - name: log-shipper
      image: busybox
      command: ['sh', '-c', 'echo WAIT FOR DB START.sh'] 
      restartPolicy: Always